/*
 * -----------------------------
 * Generated Init implementation
 * -----------------------------
 */

#include <ooc/Object.h>
#include <ooc/init_ooc.h>

extern Class ooc_classDesc(AllocArrayPtr);
extern Class ooc_classDesc(AllocPtr);
extern Class ooc_classDesc(ArrayPtr);
extern Class ooc_classDesc(BasicType);
extern Class ooc_classDesc(Bool);
extern Class ooc_classDesc(Char);
extern Class ooc_classDesc(Closure);
extern Class ooc_classDesc(Comparable);
extern Class ooc_classDesc(Complex);
extern Class ooc_classDesc(Copiable);
extern Class ooc_classDesc(Double);
extern Class ooc_classDesc(ExBadAccess);
extern Class ooc_classDesc(ExBadAlloc);
extern Class ooc_classDesc(ExBadArgument);
extern Class ooc_classDesc(ExBadAssert);
extern Class ooc_classDesc(ExBadCast);
extern Class ooc_classDesc(ExBadClass);
extern Class ooc_classDesc(ExBadDomain);
extern Class ooc_classDesc(ExBadException);
extern Class ooc_classDesc(ExBadFormat);
extern Class ooc_classDesc(ExBadInput);
extern Class ooc_classDesc(ExBadIO);
extern Class ooc_classDesc(ExBadOp);
extern Class ooc_classDesc(ExBadPosition);
extern Class ooc_classDesc(ExBadRange);
extern Class ooc_classDesc(ExBadSignal);
extern Class ooc_classDesc(ExBadSize);
extern Class ooc_classDesc(ExBadState);
extern Class ooc_classDesc(ExBadType);
extern Class ooc_classDesc(Exception);
extern Class ooc_classDesc(ExNotFound);
extern Class ooc_classDesc(ExNotImplemented);
extern Class ooc_classDesc(ExNotSupported);
extern Class ooc_classDesc(ExOverflow);
extern Class ooc_classDesc(ExSigABRT);
extern Class ooc_classDesc(ExSigALRM);
extern Class ooc_classDesc(ExSigBUS);
extern Class ooc_classDesc(ExSigFPE);
extern Class ooc_classDesc(ExSigILL);
extern Class ooc_classDesc(ExSigINT);
extern Class ooc_classDesc(ExSignal);
extern Class ooc_classDesc(ExSigQUIT);
extern Class ooc_classDesc(ExSigSEGV);
extern Class ooc_classDesc(ExSigTERM);
extern Class ooc_classDesc(ExSysIO);
extern Class ooc_classDesc(ExSystem);
extern Class ooc_classDesc(ExTestAssert);
extern Class ooc_classDesc(ExUnderflow);
extern Class ooc_classDesc(ExUnexpected);
extern Class ooc_classDesc(Field);
extern Class ooc_classDesc(Float);
extern Class ooc_classDesc(Floating);
extern Class ooc_classDesc(Function);
extern Class ooc_classDesc(Int);
extern Class ooc_classDesc(Integral);
extern Class ooc_classDesc(Long);
extern Class ooc_classDesc(LongDouble);
extern Class ooc_classDesc(LongLong);
extern Class ooc_classDesc(Method);
extern Class ooc_classDesc(Number);
extern Class ooc_classDesc(Pointer);
extern Class ooc_classDesc(SpeedTestResult);
extern Class ooc_classDesc(StaticField);
extern Class ooc_classDesc(StaticMethod);
extern Class ooc_classDesc(Test);
extern Class ooc_classDesc(TestCase);
extern Class ooc_classDesc(TestError);
extern Class ooc_classDesc(TestFailure);
extern Class ooc_classDesc(TestMessage);
extern Class ooc_classDesc(TestResult);
extern Class ooc_classDesc(TestSuccess);
extern Class ooc_classDesc(TestSuite);
extern Class ooc_classDesc(Type);
extern Class ooc_classDesc(TypedAllocArrayPtr);
extern Class ooc_classDesc(TypedAllocPtr);
extern Class ooc_classDesc(TypedArrayPtr);
extern Class ooc_classDesc(TypedPtr);

void ooc_init_ooc()
{
  ooc_classInitialize(AllocArrayPtr);
  ooc_classInitialize(AllocPtr);
  ooc_classInitialize(ArrayPtr);
  ooc_classInitialize(BasicType);
  ooc_classInitialize(Bool);
  ooc_classInitialize(Char);
  ooc_classInitialize(Closure);
  ooc_classInitialize(Comparable);
  ooc_classInitialize(Complex);
  ooc_classInitialize(Copiable);
  ooc_classInitialize(Double);
  ooc_classInitialize(ExBadAccess);
  ooc_classInitialize(ExBadAlloc);
  ooc_classInitialize(ExBadArgument);
  ooc_classInitialize(ExBadAssert);
  ooc_classInitialize(ExBadCast);
  ooc_classInitialize(ExBadClass);
  ooc_classInitialize(ExBadDomain);
  ooc_classInitialize(ExBadException);
  ooc_classInitialize(ExBadFormat);
  ooc_classInitialize(ExBadInput);
  ooc_classInitialize(ExBadIO);
  ooc_classInitialize(ExBadOp);
  ooc_classInitialize(ExBadPosition);
  ooc_classInitialize(ExBadRange);
  ooc_classInitialize(ExBadSignal);
  ooc_classInitialize(ExBadSize);
  ooc_classInitialize(ExBadState);
  ooc_classInitialize(ExBadType);
  ooc_classInitialize(Exception);
  ooc_classInitialize(ExNotFound);
  ooc_classInitialize(ExNotImplemented);
  ooc_classInitialize(ExNotSupported);
  ooc_classInitialize(ExOverflow);
  ooc_classInitialize(ExSigABRT);
  ooc_classInitialize(ExSigALRM);
  ooc_classInitialize(ExSigBUS);
  ooc_classInitialize(ExSigFPE);
  ooc_classInitialize(ExSigILL);
  ooc_classInitialize(ExSigINT);
  ooc_classInitialize(ExSignal);
  ooc_classInitialize(ExSigQUIT);
  ooc_classInitialize(ExSigSEGV);
  ooc_classInitialize(ExSigTERM);
  ooc_classInitialize(ExSysIO);
  ooc_classInitialize(ExSystem);
  ooc_classInitialize(ExTestAssert);
  ooc_classInitialize(ExUnderflow);
  ooc_classInitialize(ExUnexpected);
  ooc_classInitialize(Field);
  ooc_classInitialize(Float);
  ooc_classInitialize(Floating);
  ooc_classInitialize(Function);
  ooc_classInitialize(Int);
  ooc_classInitialize(Integral);
  ooc_classInitialize(Long);
  ooc_classInitialize(LongDouble);
  ooc_classInitialize(LongLong);
  ooc_classInitialize(Method);
  ooc_classInitialize(Number);
  ooc_classInitialize(Pointer);
  ooc_classInitialize(SpeedTestResult);
  ooc_classInitialize(StaticField);
  ooc_classInitialize(StaticMethod);
  ooc_classInitialize(Test);
  ooc_classInitialize(TestCase);
  ooc_classInitialize(TestError);
  ooc_classInitialize(TestFailure);
  ooc_classInitialize(TestMessage);
  ooc_classInitialize(TestResult);
  ooc_classInitialize(TestSuccess);
  ooc_classInitialize(TestSuite);
  ooc_classInitialize(Type);
  ooc_classInitialize(TypedAllocArrayPtr);
  ooc_classInitialize(TypedAllocPtr);
  ooc_classInitialize(TypedArrayPtr);
  ooc_classInitialize(TypedPtr);
}
